In [23]:
import numpy as np
import mmtf
import pprint

In [4]:
def print_class_dir(class_instance):
    """ Prints the dir of the given object but only the
        public methods and attributes.
    """
    public_method_list = [method for method in dir(class_instance) if not method.startswith("_")]
    pprint.pprint(public_method_list)

In [5]:
decoder = mmtf.parse("data/1sux.mmtf")
print_class_dir(decoder)

['alt_loc_list',
 'atom_counter',
 'atom_id_list',
 'b_factor_list',
 'bio_assembly',
 'bond_atom_list',
 'bond_order_list',
 'chain_counter',
 'chain_id_list',
 'chain_name_list',
 'chains_per_model',
 'decode_data',
 'deposition_date',
 'entity_list',
 'experimental_methods',
 'get_bonds',
 'get_coords',
 'group_counter',
 'group_id_list',
 'group_list',
 'group_type_list',
 'groups_per_chain',
 'ins_code_list',
 'mmtf_producer',
 'mmtf_version',
 'model_counter',
 'num_atoms',
 'num_bonds',
 'num_chains',
 'num_groups',
 'num_models',
 'occupancy_list',
 'pass_data_on',
 'r_free',
 'r_work',
 'release_date',
 'resolution',
 'sec_struct_list',
 'sequence_index_list',
 'space_group',
 'structure_id',
 'title',
 'unit_cell',
 'x_coord_list',
 'y_coord_list',
 'z_coord_list']


In [12]:
decoder.entity_list

[{'description': 'Triosephosphate isomerase, glycosomal',
  'type': 'polymer',
  'chainIndexList': [0, 1],
  'sequence': 'MASKPQPIAAANWKCNGSESLLVPLIETLNAATFDHDVQCVVAPTFLHIPMTKARLTNPKFQIAAQNAITRSGAFTGEVSLQILKDYGISWVVLGHSERRLYYGETNEIVAEKVAQACAAGFHVIVCVGETNEEREAGRTAAVVLTQLAAVAQKLSKEAWSRVVIAYEPVWAIGTGKVATPQQAQEVHELLRRWVRSKLGTDIAAQLRILYGGSVTAKNARTLYQMRDINGFLVGGASLKPEFVEIIEATK'},
 {'description': 'SULFATE ION',
  'type': 'non-polymer',
  'chainIndexList': [2, 3, 4, 5, 6, 7, 8],
  'sequence': ''},
 {'description': '3-(2-BENZOTHIAZOLYLTHIO)-1-PROPANESULFONIC ACID',
  'type': 'non-polymer',
  'chainIndexList': [9],
  'sequence': ''},
 {'description': 'water',
  'type': 'water',
  'chainIndexList': [10, 11],
  'sequence': ''}]

In [14]:
decoder.group_list[0]

{'groupName': 'ALA',
 'atomNameList': ['N', 'CA', 'C', 'O', 'CB'],
 'elementList': ['N', 'C', 'C', 'O', 'C'],
 'bondOrderList': [1, 1, 2, 1],
 'bondAtomList': [1, 0, 2, 1, 3, 2, 4, 1],
 'formalChargeList': [0, 0, 0, 0, 0],
 'singleLetterCode': 'A',
 'chemCompType': 'L-PEPTIDE LINKING'}

In [26]:
print(decoder.ins_code_list[0:5])
print(np.unique(decoder.ins_code_list))

['\x00', '\x00', '\x00', '\x00', '\x00']
['']


In [24]:
print(decoder.occupancy_list[0:5])
print(np.unique(decoder.occupancy_list))

[1. 1. 1. 1. 1.]
[0.5 1. ]


In [29]:
print(decoder.sec_struct_list[0:5])

[7 7 7 7 7]


In [32]:
print(decoder.b_factor_list[0:5])

[41.16 41.46 40.38 42.01 41.41]


In [33]:
print(decoder.sequence_index_list)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24